#pragma config(UserModel, "../includes/ClawBot_Config.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Load helpful commands
#include "../includes/ClawBot_wayClear.h"
#include "../includes/ClawBot_autoDrive.h"
#include "../includes/ClawBot_autoDriveTime.h"		// (speed, mSec)
//#include "../includes/ClawBot_autoDriveDist.h"
#include "../includes/ClawBot_autoTurn.h"
#include "../includes/ClawBot_autoTurnTime.h"
#include "../includes/ClawBot_autoTurnGyro.h"

// Maze solver
task main()
{
	// Completely clear out any previous readings
	SensorType[gyro01] = sensorNone;
	wait1Msec(500);
	// Reconfigure the post as a Gyro sensor and allow time for calibration
	SensorType[gyro01] = sensorGyro;
	wait1Msec(1500);

	// default mission = do nothing
	int mission = 0;

	while(true)
	{
		//
		while(mission == 0)
		{
			autoDrive(0);
			// if button pressed add 1 mod 2 to mission (will equal zero if == 2)
			//if(SensorValue[button01] == 1)
			//{
			//	mission = 1;
			//}
		}

		while(mission == 1)
		{
			// Move forward
			if(wayClear())
			{
				autoDrive(30);
			}

			// if there is an obstruction at N, turn CCW
			if(wayClear() == false)
			{
				// stop drive
				autoDrive(0);

				// turn CCW
				autoTurnGyro(30, 90);

				// stop drive
				autoDrive(0);

				// if there is an obstruction at E, turn 180 CW
				if(wayClear() == false)
				{
					// turn 180 CW
					autoTurnGyro(30, 180);

					// stop drive
					autoDrive(0);

					// if there is an obstruction at 90, turn CW 90
					// tells robot to go back
					if(wayClear() == false)
					{
						// turn CW 90
						autoTurnGyro(30, -90);

						// stop drive
						autoDrive(0);
					}
				}
			}
		}
	}
}
