#pragma config(Sensor, in1,    gyro01,         sensorGyro)
#pragma config(Sensor, dgtl1,  sonar01,        sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  quad01,         sensorQuadEncoder, reversed)
#pragma config(Sensor, dgtl5,  quad02,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  button01,       sensorTouch)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FRDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FLDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RRDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RLDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           clawMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int wheelDiameter = 4;	// set the wheel diameter
int encoderTicks = 360;	// number of ticks in a rev
int q1, q2, q3, q4;			// variables to record distances for testing
int LRdiff;
int battLvl = nAvgBatteryLevel;
